language: node_js
node_js:
- 12
notifications:
  email:
    recipients:
    - walimmorris@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: fEnpHJ4mfDKhNEW/yUhAA3eVRBgiAQcGHCEIT1MmJ9Sm89mPk8OVrOJeBsdFeqQkn5GElW5kom1Tw6GgWmDpkG/KqBT9cfiWDYDSZ2uxffcvCtOKu/G4WLuOjVeadHg6pD2I6cKkxI87tQ4eJoFD/zpuYaB1y3v3oVYLtqolOB6XVjBriMBALJ3laR4WW8xNVgtKazZoFX87G2oS6LYG4jckgyhwLSd30hLyRxEf+jUMutGhuS/oLwMS4opDNMNsQonSxcqHKq2j2mTySdvVtisi9sEP8kmRd7RAfuq8eI8dtkFXoDNwWGSJ2AiBXhF/UOq5xwK6LiPNbCJIw64Lhcnv6sMuBqBvf9lAuxTi2cFjsKDkQnmywPCTigsJkfiZwsMS+794wIAykHe7UbynXW/jI4BC4DxSqjQ/yebpE+sn30KCZQrWWwqud66fnCncY/4cAZaTJ0uL2XIsO3AWuwT9Np1Jx0sApADaDuwCus08HU9ujtefYSjN3Od4q+OWSENIfeQhdtwrQn0FXH870rywYb2ROuL1ftPm1AAXJkvTf4rJKW01vTTgQHImrUPjsFfMmRKk4Oh7kociDsqAe5aYRnOZecXYNPBRx3Ghuk7LeVYF+ORYagq4dwWkmttES3ZqmAbp0QuO07vSQs3BlqzLRHz0GoEXX4Bqbpv+ZKc=
