language: node_js
node_js:
- 12
notifications:
  email:
    recipients:
    - walimmorris@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  app: foster-awareness
  api_key: $HEROKU_API
