language: node_js
node_js:
- 12
notifications:
  email:
    recipients:
    - walimmorris@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: C7BQKcCYq0ztbt68jm+iRkGtOP9FR7uIao/AjKNkp2hc4rhO3ZKUXP+USMkd444qPe/1CuQZkt13uLrS1imgpHjCCJxtMtjrBfJnMNTJGepmhDEtR8/6pkoktideCo1geYwWLmDCb/z9dNLp4d6OixxxYUBlaU+MIyKLEwnv1ktZKpb96rTFjggPvfIaorme7n2DdcLV4NGZewe0VO1p/1Baq+HEAT1hpwj4EMmEOmyQps+tu1iBnqrWcAee0wjNu983ccQLQam0+OC8grrs8lTKZUXW1L+yQqYxCadhJ8oYN1ZVxhtfL8pcdNevzJwDhwTmYJ6Mo3fEOZ5lPfbCr7AJEH7b44PjostBHZ67wt13sIgf8YBBQur36vYvX/JJxZtisCovSGmPYi7PIjOR3q4w5vgfIBcx42XHWjbfWtewCYgnjH3SdN72QtKw4+DZ0Zq3uHYTlrM5gTG/zV96VdG2wQSkw7NnnWP3dlklkvC/PYyq5e35Qlmv1T+fvGUKunxjaaUGQ8loanpLiI9kYvlsEidvEMVzjwkF8iAhpl+kLEecTBXQ9VXXf0d/XzrQuX0XTCVAn+BX8/6Rjh9RwH0yeY0gCtYvr7Md9sTjdXmhqoLvHzwFfX2s3SXWlQT0bsyVo8RC6Vr93tFFUDzueFE0OJgziIht8SjtMnGPa1c=
