language: node_js
node_js:
- 12
notifications:
  email:
    recipients:
    - walimmorris@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: dDEPF2RmkD1Is3QrVeROMLyGIpdLGlB1TPpDk236AK/tGJg2SUv7fmjKIFyphSo1QV8XgXIakSBUOGhSj+A4VkRI72bwfDBQiwbeBdZ16Ohl/CZ4YZl7U8+K/M6p3KyoAETYynsM4QjrqMhU25SdbugU8gCDdDaPz+acYywyldjOSezzWDQbMyz+0OJTgrVjCjaeqMOwFORehO/buSvWc7NHJ/KNSFIqv3KwAh9ELIyWT3Gyi4kQQhxFEktf5ERsrlcYI07VzpmV47IoNED8ZANnemRDzDMXYbdbyZUFIip7E7lCv0VYeIBzCaWsLURtGU1jH2kOftgSstoSQokWT3E++pTHmdnkdcRZ9xNmCpTgB+0KaVUKFbD+DxvI+c3SqWDWgW7OzpXUHJbPlyV7i58OkflJaa0K2rZvflEy0iwbvW840g4k8yks8JQihl7jLlilVAFjTqTmiAnn5iMvRKbVKOZ0szn+AS4fsQp4Tc+BXGZPfQj7We+ub+qU4/7+XRQnSA5h55OBMnygvi8LeRV7SWfQzHwjIbUNUfR67pC3IH+FWvSfEXvfa1zmcYlLExsiCEw6GD63TcEuKb1G5MULci3bYTCmyQAtVojYigekNyGsW7oxwxEFSTvQQ+T+JUzuG9DdUSafwkmtImIzGJMG9BNiq09MuOsjTNmIzfE=
