language: node_js
node_js:
- 12
notifications:
  email:
    recipients:
    - walimmorris@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: PZVixW5QR8nXKsN7EP2U9DS5c4udRLQLhcU7mCSqXLi6UvUWRmmhHSBdTxR5EqA4wCDmOwXt7sZvw+EXOgrS5+T+4s17Q3miyULBOZzzGDegaDKtTycIItUkCFQqXZRDb/IWJ93PxY4M43boR7wYa8Kd5W80IQh7e1SrSL8KIGGd3AdNVZsNBlkabPvHHUt9avfC/QRH8EqxHkJVuG0U84e4ZXsHgtFa8hnvdc0+Gu4bKXrnRlPvMnYPSJOdZ2YJqKRfN83Zz8X3OGoUDRSOPYBBgpNU4DfmB3jf/Llh5hKpvZvPfdHuRKSBHoazA0E6dEE+SEZgAtVzM08vInlmLoORT5QaFcLI9Vpvf6jbRbJnEOQ1z5DtdfSqfXAk0r34nYpVtZ1COHzLymU2UST32iobCia4G+hTRVoeRBPwPWU2Kc3SMmP+I+cw2ekfmc8YQEJkRJqLY9pOu2ojE5D3Kvl46yJgdUzAFZsroIHRftKM7x8/L0pYOOkiBSodZB5jQSaCD/O7bj2WV4vqjGL8EGXcM7erOcpN/dNkSagZzLbjKdwscroUJY8V+HdoxBAnES75EQDQ5R9nnQKGAgvODBNiFf3Tz1as/RSobPi23aLXNkBKbApDymzrkfyqlmXuF63mYkdZTSdPe+ZcrHDr5kWzYYNdrbdSkikPw7qgbbE=
  app: Foster Awareness
