language: node_js
node_js:
- 12
notifications:
  email:
    recipients:
    - walimmorris@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: h5ONDAjBvPZd0mtRps/uw4/mEu+FhUoc3us8ieyawfn4NDomxlLLdXAqn0VrVGSBIejaA67XxgB2xPipaL1W9DbA1QcGCdVC3jf9Q8rCoicLAWI/iqCMX7v7wpA0BonQ9Zcs4P/rpMld+Kf8KqtOA2kOF5CvbMtsVbtKGAR2AoFLkHPPUu153f+Uv/BO8aOhBGxmDRhxfYWrsFa/x39vqYAG1JUMBTJG+Ii9dbIVz68KHPQpZHVa+38G18A4CvnbSTtpA61MKY6Goq7POiDhDRmseuvF8jD/oqL4eBrXWylNi+t/vJNDVHEydWAt9lKHGhC7IxsbNc2fXgEfx2riv4cFygIoXTIYfphvUMrF4y4JhVQuOCdZJvVNwyhmuCPLpCBiJdQEmfp7ieXyldttKQhvFECkj9CsWrjZMj6+mV06UNmLQCDuBrZyWI9rLaEoxigPK0KmgzEu6czeBSK6BKzYMfwLOxWDSMzh9yWvzBd1RWwbRwRHX0IyOzzN7vtv7X+XQxNNCUFHOFJ0ugLlraTybX5RnDI/+0R3qFXs22gxFOrnxsPBa1J9v4P9ph8NU04XuAUF5KAxIyVz4WJrC7Tb0JVsPG/LNEeIiahsHd4d6l93d3ymJmm4J6a/qMs2KXiQVgkgywb3dGJuoVslYFyvpEDzGlhlQ4pqvdGX0aY=
